### ISSUE TITLE
2 issues in one, not related to the workings of the mod

### ISSUE THREAD

**Issue by RepoDraghon** [ate47/Xray#11]
1... The mod in the Twitch app shows that the 1.0.3-1.15.2 version is for the "Game Version: 1.13"
might want to update that but not necessary as it shows up for the 1.15.2 version too

2... when installed (Forge version) it shows both the Forge and Fabric versions installed in the Versions window but isn't showing in the installed mods window...

Both issues may just be Twitch's fault but might be worth looking into on your end...

![Screenshot (61)](https://user-images.githubusercontent.com/8423696/83957168-958ec800-a81a-11ea-997a-0cae3ae7e218.png)
![Screenshot (62)](https://user-images.githubusercontent.com/8423696/83957170-96bff500-a81a-11ea-8579-651e41baef9f.png)
![Screenshot (63)](https://user-images.githubusercontent.com/8423696/83957172-97588b80-a81a-11ea-9c13-3bf4e97662fa.png)

**Comment by ate47** [comment]
I can’t reproduce it so I think it was patched, if this is occurring again, try removing the version for the other mod launcher
