### ISSUE TITLE
add entity xray plssss

### ISSUE THREAD

**Issue by MgHackerBr** [ate47/Xray#33]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Your Minecraft Version** 1.18.1
Minecraft version wanted: 1.18.1 / 1.19
Mod loader wanted (Fabric/Forge/Rift): FABRIC / forge if possible,.....

**Additional context**

ADD ENTITY XRAY, PLS

**Comment by ate47** [comment]
Can you describe a bit more what an “entity xray” is?

**Comment by MgHackerBr** [comment]
just like you made in blocks but for entities, just lines pointing to it or like the bodycolliser, for show the distance specific entity, like, if i want to look for villagers, the mod will draw a line that point to it, or a for example, a fox, upcoming mob like frog, specific mob like an bat under a cave, or for just cows. without requirements of maps and these things. if possible pls <333333

**Comment by ate47** [comment]
added in 2.0.0
