### ISSUE TITLE
no xray, only full bright

### ISSUE THREAD

**Issue by Jessman5** [ate47/Xray#34]
**Describe the bug**
All the mod does is the full bright feature. Regardless what ores or other blocks are in the cave or xray lists. when I activate xray or cave mode, it does full bright instead.

**To Reproduce**
load the mod, try to use it.

**Crash report or logs**
none.

**Expected behavior**
giving the xray and cave feature

**Minecraft version**
Minecraft version: 1.18.1
Mod loader (Fabric/Forge/Rift): Forge 39.0.9

**Comment by ate47** [comment]
Do you have optifine or another mod installed?

**Comment by Isehaowo** [comment]
> Do you have optifine or another mod installed?

well. i have same issues but i use optifine

**Comment by ate47** [comment]
> > Do you have optifine or another mod installed?
> 
> well. i have same issues but i use optifine

The mod is currently not compatible with Optifine/Optifabric (#23)

**Comment by Jessman5** [comment]
Are you guys going to fix that?

**Comment by ate47** [comment]
Nop ;)

Duplicate with #23
