### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by bulkasmakom1** [ate47/Xray#36]
Server crashes on startup as title says. I`m playing on my server and started literally yesterday. Then i left the game and stopped server. Next day server just restarted again and again 

Minecraft version: 1.16.5
Mod loader (Fabric/Forge/Rift): Forge
Mods loaded with the mod
can i just say it`s modpack ragnamod 6 and leave a link
https://www.curseforge.com/minecraft/modpacks/ragnamod-vi?__cf_chl_jschl_tk__=LZeqjr_JFGJvDUdX0Qts1LOeYh3pxv76KFnUaO.JNJg-1640884177-0-gaNycGzNEP0

[crash-2021-12-30_03.03.49-fml.txt](https://github.com/ate47/Xray/files/7793880/crash-2021-12-30_03.03.49-fml.txt)

If this is not a proper place for this issue, please let me know where can i seek any info on that

**Comment by ate47** [comment]
This is the issue page of the mod Xray, this mod is a client mod and isn't installed at all in your Minecraft so this issue isn't relevant at all here.

Also, in your crash report you have these lines:
```
Failure message: Immersive Engineering (immersiveengineering) encountered an error during the common_setup event phase
		java.util.ConcurrentModificationException: null
	Mod Version: 1.16.5-5.0.6-141
	Mod Issue URL: https://github.com/BluSunrize/ImmersiveEngineering/issues
```

We can read that the mod crashing your game/server is **Immersive Engineering** (not Xray) and that they have a issue page here: https://github.com/BluSunrize/ImmersiveEngineering/issues

I'm closing the issue, try to create an issue on their page.

**Comment by bulkasmakom1** [comment]
Oh my god, i posted this in wrong github page, sorry for wasting your time
thanks for your fast reply, I really appreciate it!
