### ISSUE TITLE
Error loading mod: java.lang.IllegalStateException: Rendersystem called from wrong thread 

### ISSUE THREAD

**Issue by Limelie** [ate47/Xray#39]
**Describe the bug**
Hi! I received a crashreport, I don't know much about this and English is not my first language but I hope it helps to recognize the error

![Screenshot_1](https://user-images.githubusercontent.com/98111066/150382119-c4e922e2-927d-4805-a615-cd88d43655a7.png)
**Crashlog**
[crash-2022-01-20_10.20.58-fml.txt](https://github.com/ate47/Xray/files/7906965/crash-2022-01-20_10.20.58-fml.txt)

Tysm in advance

**Comment by ate47** [comment]
Fixed and uploaded, you can find the 1.18 Forge version [here](https://www.curseforge.com/minecraft/mc-mods/xray-1-13-rift-modloader/files/3614846) or via the CurseForge launcher.

**Comment by ate47** [comment]
Little update because I didn't saw it during the reading of the Crash Report, this Xray mod is incompatible with Optifine #23.

So the mod won't crash, but the Xray won't work (maybe the Tracers/ESP)

**Comment by Limelie** [comment]
Thanks! It is very nice of you to do it so fast, I hope soon it can be compatible with Optifine, it would be of great comfort :D
