### ISSUE TITLE
zn_cn translation uncomplete

### ISSUE THREAD

**Issue by ate47** [ate47/Xray#46]
@loonybtard, the translation files have been updated on the forge-1.17-v2 branch, you were the one that made the ``zn_cn.json``, can you complete it with the new translation?

(If someone reading this can do it before the answer, you can make a PR)

**Comment by GodGun968** [comment]
I have made a new one, you can close this issue, I will continue to update the zn_cn translation in the future

**Comment by GodGun968** [comment]
By the way, when will make 1.19 forge

**Comment by ate47** [comment]
In this issue, I'm talking about the future update file, with more translations than the current one, this future update is still only for the forge-1.17-v2 version

In this file: https://github.com/ate47/Xray/blob/forge-1.17-v2/src/main/resources/assets/atianxray/lang/en_us.json

**Comment by GodGun968** [comment]
small problem

**Comment by GodGun968** [comment]
Is there a compiled file?it is used to check my sinicization

**Comment by GodGun968** [comment]
I have translated,I just need a compile file to verify my localization and I can upload new localizations

**Comment by GodGun968** [comment]
I really didn't find the compiled file

**Comment by GodGun968** [comment]
can you give me a compiled file?

**Comment by ate47** [comment]
done in #57, thanks :)
