### ISSUE TITLE
Incompatibility Rubidium(Sodium Fork)

### ISSUE THREAD

**Issue by lpopovic7519rn** [ate47/Xray#51]
**Describe the bug**
Incompatible with Rubidium(Sodium fork).
When trying to activate xray or cave finder, the screen flashed as if reloading chunks and doesnt show caves or ores. Once the rubidium mod is deleted, the xray functions as normal.

**To Reproduce**
Install rubidium and xray. Press xray or cave finder key in game.

**Expected behavior**
Being able to see ores and caves

**Minecraft version**
Minecraft version: 1.18.3
Mod loader (Fabric/Forge/Rift): Forge

**Additional context**
Tried to add xray to "Better Minecraft" modpack, it behaved as mentioned above. Started removing some mods that were incompatible with Optifine(logic: if its incompatible with Optifine it might be incompatible with xray). Turned out Rubidium mod was one of the incompatible mods for both.

**Comment by ate47** [comment]
Duplicate with #50
