### ISSUE TITLE
This is a new Chinese translation file

### ISSUE THREAD

**Issue by GodGun968** [ate47/Xray#52]
This is a new Chinese translation file
The original translation is too old and there are many words that have not been translated
So I hope you can use this new translation file
Thank you!
[zh_cn.zip](https://github.com/ate47/Xray/files/8885688/zh_cn.zip)

**Comment by ate47** [comment]
Can you create a pull request to add it?

**Comment by GodGun968** [comment]
> Can you create a pull request to add it?

ok
