### ISSUE TITLE
When esp is enabled, there will be some errors on display for chests and signs

### ISSUE THREAD

**Issue by GodGun968** [ate47/Xray#56]
![image](https://user-images.githubusercontent.com/67826085/174842963-65a9d368-ff6d-4deb-ad0b-f4c6f1cd0d25.png)
![image](https://user-images.githubusercontent.com/67826085/174843920-ff5471d2-fbc2-43ee-bad1-e341f332ce96.png)

After enabling:
![image](https://user-images.githubusercontent.com/67826085/174843067-7406f3a6-7171-40b1-b328-a5bee3bfa04f.png)
![image](https://user-images.githubusercontent.com/67826085/174843954-ca5f71cf-912f-4888-908d-ec0db92a5a60.png)

Minecraft version: 1.19
Mod loader : fabric 0.14.8

I don't know if it's a bug, but at least I don't think it should happen
I tried again
To ensure the accuracy of the results, I disabled all mods, only xray and api
bug still exists

**Comment by ate47** [comment]
Duplicated with #75
