### ISSUE TITLE
Mod 1.19 download requires 1.17+ and -1.18

### ISSUE THREAD

**Issue by shi-gg** [ate47/Xray#61]
**Describe the bug**
I downloaded the jar file for minecraft 1.19 on [curse forge](https://www.curseforge.com/minecraft/mc-mods/xray-1-13-rift-modloader/files/3832345) but in game the FML tells me that it requires 1.17+ and -1.18

**To Reproduce**
1. download https://www.curseforge.com/minecraft/mc-mods/xray-1-13-rift-modloader/files/3832345
2. install it (move into mods)
3. launch 1.19

**Expected behavior**
it is supposed to be installed as normal mod

**Screenshots**
![image](https://user-images.githubusercontent.com/71079641/177516178-d2ead160-04f4-412d-8bce-eaaec1137f6b.png)

**Minecraft version**
Minecraft version: 1.19
Mod loader (Fabric/Forge/Rift): Forge

**Comment by ate47** [comment]
You downloaded the Fabric version, which is not compatible with Forge, you don't have a Forge release available yet.
