### ISSUE TITLE
enchanting table book for esp

### ISSUE THREAD

**Issue by chonkerbonker** [ate47/Xray#65]
### Mod version

2.0.1

### Minecraft version

1.19

### Mod loader

Fabric

### Description of the request

There is no enchanted book in the entity selector, I would really like there to be a way to trace an enchanting table.

### Do I want to contribute to make it?

No

**Comment by ate47** [comment]
Enchanting tables aren't entities (title entities), so it's probably linked with this bug: #22

**Comment by ate47** [comment]
Duplicated with #69
