### ISSUE TITLE
fullbright doesnt work

### ISSUE THREAD

**Issue by user00000000000000** [ate47/Xray#68]
### Mod version

2.0.5

### Minecraft version

1.19.2

### Mod loader

Fabric

### Description of the issue

When I use xray all the ores and mobs are dark(fullbright enabled)

### Excepted behavior

all the things is bright

### How to reproduce

1.go in a cave
2.turn on fullbright
3.turn on xray

**Comment by Xetaxheb** [comment]
Fullbright may not work with shaders

**Comment by ate47** [comment]
No news if it was the shaders or not, so I assume it was
