### ISSUE TITLE
Chest ESP + Tracer

### ISSUE THREAD

**Issue by kit-nine** [ate47/Xray#69]
### Mod version

2.0.4

### Minecraft version

1.19

### Mod loader

Forge

### Description of the request

I'd like to be able to trace chests in addition to other entities. This isn't an option currently.

### Do I want to contribute to make it?

No

**Comment by Xetaxheb** [comment]
Chests aren't entities.. use xray mode

**Comment by ate47** [comment]
> Chests aren't entities.. use xray mode

He wants to use the tracer, not the ESP, so this is a relevant issue

**Comment by ate47** [comment]
Done in Fabric 1.19 2.1.0, need Forge port
