### ISSUE TITLE
Mod is not compatible with Optifine/Optifabric (1.15.2)

### ISSUE THREAD

**Issue by ilepow34** [ate47/Xray#7]
The 1.15.2 Fabric release of this mod is not compatible with Optifine. When Optifine is loaded alongside this mod via Optifabric, toggling xray mode on only reloads the blocks, and does not affect whether their sides are rendered.

**Comment by TheRand0m** [comment]
Problem still persists, when toggling xray the blocks aren't affected.

Fabric version: 1.15.2-build 14

- With OptiFine 1.15.2 HD U G1 pre9,
-  optifabric-1.0.0-beta4.jar, 
- Fabric API 0.4.32 build 292, 
- voxelmap 1.15.2

**Comment by RepoDraghon** [comment]
Can confirm not working with latest 1.15.2 Optifine... screen flashes but no blocks are affected... but it does act like a full bright...

**Comment by ate47** [comment]
#23 duplicate
