### ISSUE TITLE
X-ray does not work, night vision works

### ISSUE THREAD

**Issue by kazaminosuke** [ate47/Xray#79]
### Mod version

2.04

### Minecraft version

1．19.2

### Mod loader

Forge

### Description of the issue

X-ray does not work, night vision works.

### Excepted behavior

no

### Obtained behavior

night vision 

### Do I want to contribute to fix it?

Yes

### Something else?

no

**Comment by kazaminosuke** [comment]
https://user-images.githubusercontent.com/99616465/200150518-9be44d14-4683-43f2-a33a-e0e4972a4591.mp4

**Comment by ate47** [comment]
Can you send the mods list?

**Comment by maykin6789** [comment]
try to remove OptiFine mod if ur install it.

**Comment by V-Tom** [comment]
> try to remove OptiFine mod if ur install it.

Thank you man, it works for me
