### ISSUE TITLE
XrayMod (atianxray) has failed to load correctly.

### ISSUE THREAD

**Issue by ThomasC03** [ate47/Xray#87]
### The bug occurs without having Optifine or Optifabric installed? (Optifine bugs won't be fixed)

- [X] Yes, I don't have Optifine install.

### Mod version

2.0.4

### Minecraft version

1.19.3

### Mod loader

Forge

### Description of the issue

java.lang.reflect.InvocationTargetException: null
[crash-2022-12-15_22.53.11-fml.txt](https://github.com/ate47/Xray/files/10242540/crash-2022-12-15_22.53.11-fml.txt)

I am using MultiMC and also have Xaero's Mini Map and World Map installed

### Excepted behavior

For the mod to work

### Do I want to contribute to fix it?

None

**Comment by R-3-X-Y** [comment]
It seems to be an error with the mod itself, as I tested it with just the Xray Mod and I am getting the same error.

**Comment by ate47** [comment]
It was an issue with the 1.19.3, it's fixed, you can download the latest version here: https://www.curseforge.com/minecraft/mc-mods/xray-1-13-rift-modloader/files/4276628 (wait few minutes after this comment if not available)
