### ISSUE TITLE
some blocks visible even when not selected

### ISSUE THREAD

**Issue by CootieDwagon** [ate47/Xray#93]
### The bug occurs without having Optifine or Optifabric installed? (Optifine bugs won't be fixed)

- [X] Yes, I don't have Optifine install.

### Mod version

2.0.5

### Minecraft version

1.19.2

### Mod loader

Fabric

### Description of the issue

i can still see Vines, Spider webs, grass (not the grass block but grass), minecart rails, banners. chests, torchs, lanterns, anvils, and a few other blocks when i toggle on thje X-Ray. even when i have made it so the X-Rar is not supposed to show those blocks

### Excepted behavior

i was expecting to not see those blocks unless i have the mselected in the "Xray" list of blocks to "see"

### Obtained behavior

i am able to see those blocks i listed off, which i do not think should happen unless i set to appear on the X-Ray

### How to reproduce

- step 1: install the mod for Fabric
- step 2: load up either single player or a modded server with the mod
- step 3: toggle on the X-ray and you will see blocks that are not even on the list

### Do I want to contribute to fix it?

No

**Comment by ate47** [comment]
Duplicated with #22, I don't know when I will fix it
