### ISSUE TITLE
Xray not hiding blocks when using Oculus Shaders

### ISSUE THREAD

**Issue by Gamemassa** [ate47/Xray#97]
### The bug occurs without having Optifine or Optifabric installed? (Optifine bugs won't be fixed)

- [X] Yes, I don't have Optifine install.

### Mod version

2.3.1

### Minecraft version

1.20.1

### Mod loader

Forge

### Description of the issue

I use your Xray mod in my custom Fabric modpack with Iris and it works fine, but when I use it in my custom Forge modpack with Oculus (which is an unofficial Forge port of Iris), your Xray mod doesn't hide blocks as it's supposed to.

### Excepted behavior

Here is your Xray mod on its own, working as intended.

![image](https://github.com/ate47/Xray/assets/18667108/aa07a8e8-47b2-474a-bfdc-ad98ef9060ad)

### Obtained behavior

When using it with Oculus, none of the Xray mod features work.

### Do I want to contribute to fix it?

Maybe

**Comment by Gamemassa** [comment]
@ate47

**Comment by ate47** [comment]
Dupe with #50

**Comment by Gamemassa** [comment]
> Dupe with #50

Does that mean it's not getting fixed?
