### ISSUE TITLE
xray gets detected on server even when not doing anything

### ISSUE THREAD

**Issue by skibidibada** [ate47/Xray#98]
i dont know if this is a bug or a feature so i'm writing here, when logging onto a server and doing nothing, when you have the xray mod in your mods folder the server will detect that you have it and ban you

**Comment by ate47** [comment]
lol

**Comment by skibidibada** [comment]
i dont understand what you mean by that, can you explain?

**Comment by ate47** [comment]
Don’t cheat on servers if it’s not allowed
