### ISSUE TITLE
Failed to load X-Ray Mod Version 2.2.0, 1.19.3 Forge

### ISSUE THREAD

**Issue by DrgonRose** [ate47/Xray#99]
### The bug occurs without having Optifine or Optifabric installed? (Optifine bugs won't be fixed)

- [X] Yes, I don't have Optifine install.

### Mod version

1.19.3 (2.2.0)

### Minecraft version

1.19.3

### Mod loader

Forge

### Description of the issue

I tried to load the mod, but at the start of Minecraft it crashes instantly. I´ve attached below the crashlog, latestlog, and a screenshot of the minecraft error message. 

I´t also doesn´t work with the Mod Version 2.0.5

I hope thats enough for the problem.
And yes Optifine is NOT installed.

If you need anything else just contact me.

### Excepted behavior

load minecraft normally

### Obtained behavior

it crashes instantly

### How to reproduce

- install forge
- drag your xray mod in folder
- start minecraft
- crash minecraft

### Do I want to contribute to fix it?

None

### Something else?

![image](https://github.com/ate47/Xray/assets/99148124/9072521f-8efa-4cc6-9370-bf68fba12e3d)
[crash-2023-07-17_22.45.19-fml.txt](https://github.com/ate47/Xray/files/12073799/crash-2023-07-17_22.45.19-fml.txt)
[latest.log](https://github.com/ate47/Xray/files/12073800/latest.log)

**Comment by ate47** [comment]
XrayMod-2.2.0.jar
![image](https://github.com/ate47/Xray/assets/1580223/9d314d70-82be-4922-b916-4ff2a57412c0)

**Comment by DrgonRose** [comment]
I´m sorry I´ve got the mod from a site where they mixed up the version of your mod and the minecraft version. And I got this github page through the logfile.
But thanks for the fast reply and that you pointed me out the correct version.

The Mod works fantastic. :)
